"""InvTorch: Setup https://github.com/xmodar/invtorch"""
from setuptools import setup

setup(
    name='invtorch',
    version='0.1.0',
    description='InvTorch: Memory-Efficient Invertible Functions',
    url='http://github.com/xmodar/invtorch',
    download_url='http://github.com/xmodar/invtorch',
    author='Modar M. Alfadly',
    author_email='modar.alfadly@gmail.com',
    license='Apache-2.0',
    packages=['invtorch'],
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    zip_safe=False,
    python_requires='>=3.6',
    install_requires=['torch>=1.10.0'],
    keywords=['deep learning', 'pytorch', 'AI'],
    classifiers=[
        'Environment :: Console',
        'Natural Language :: English',
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        'Topic :: Scientific/Engineering :: Artificial Intelligence',
        'Topic :: Scientific/Engineering :: Image Recognition',
        'Topic :: Scientific/Engineering :: Information Analysis',
        'License :: OSI Approved :: Apache Software License',
        'Operating System :: OS Independent',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
    ],
)
